global using MediatR;
global using Activity.Application;
global using FluentValidation;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Activity.API;
global using Activity.Infrastructure;
global using HealthChecks.UI.Client;
global using Activity.Application.Exceptions;
global using Microsoft.AspNetCore.Mvc;